[eve]
defeat = 55
victory = 83
draw = 45

[total]
defeat = 69
victory = 99
draw = 43

[squeak]
defeat = 18
victory = 32
draw = 22

[mortis]
defeat = 3
victory = 10
draw = 7

[alli]
defeat = 26
victory = 41
draw = 17

[mandy]
defeat = 69
victory = 99
draw = 43
